package course1;

import java.awt.EventQueue;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import Util.ArrayUtils;
import Util.JTableUtils;
import Util.SwingUtils;

/**
 * Основное окно приложения
 */
public class MainJFrame extends javax.swing.JFrame {

    private JFileChooser openJFileChooser = null;
    private JFileChooser saveJFileChooser = null;

    public MainJFrame() {
        initComponents();

        JTableUtils.initJTableForArray(inputJTable, 40, true, true, true, true);
        JTableUtils.initJTableForArray(outputJTable, 40, true, true, true, true);
        EventQueue.invokeLater(() -> {
            try {
                inputJTable.setRowHeight(((JScrollPane)inputJTable.getParent().getParent()).getColumnHeader().getHeight());
                outputJTable.setRowHeight(((JScrollPane)outputJTable.getParent().getParent()).getColumnHeader().getHeight());
            } catch (Exception ignored) {
            }
        });

        SwingUtils.initLookAndFeelMenu(lookAndFeelJMenu);

        openJFileChooser = new JFileChooser();
        saveJFileChooser = new JFileChooser();
        openJFileChooser.setCurrentDirectory(new File("./input"));
        saveJFileChooser.setCurrentDirectory(new File("./input"));
        FileFilter filter = new FileNameExtensionFilter("Text files", "txt");
        openJFileChooser.addChoosableFileFilter(filter);
        saveJFileChooser.addChoosableFileFilter(filter);

        saveJFileChooser.setAcceptAllFileFilterUsed(false);
        saveJFileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
        saveJFileChooser.setApproveButtonText("Save");
        
        systemOutJTextArea.setEditable(false);
    }

    private void showSystemOut(Runnable action) {
        PrintStream oldOut = System.out;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            System.setOut(new PrintStream(baos, true, "UTF-8"));        
        
            action.run();
        
            systemOutJTextArea.setText(baos.toString("UTF-8"));
        } catch (UnsupportedEncodingException impossible) {
        }
        System.setOut(oldOut);
        outputJTabbedPane.setSelectedComponent(outputConsoleJPanel);
    }
    
    private void showScalar(int result) {
        outputJTextField.setText("" + result);
        outputJTabbedPane.setSelectedComponent(outputScalarJPanel);
    }
    
    private void showArray(int[] array) {
        JTableUtils.writeArrayToJTable(outputJTable, array);
        outputJTabbedPane.setSelectedComponent(outputJTableJPanel);
    }
    
    private void showArray(int[][] array) {
        JTableUtils.writeArrayToJTable(outputJTable, array);
        outputJTabbedPane.setSelectedComponent(outputJTableJPanel);
    }
    
    private void showArray(List<Integer> list) {
        int[] array = ArrayUtils.toPrimitive(list.toArray(new Integer[0]));
        JTableUtils.writeArrayToJTable(outputJTable, array);
        outputJTabbedPane.setSelectedComponent(outputJTableJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJPanel = new javax.swing.JPanel();
        task1JButton = new javax.swing.JButton();
        task1NJSpinner = new javax.swing.JSpinner();
        task1NJLabel = new javax.swing.JLabel();
        task2NJLabel = new javax.swing.JLabel();
        task2NJSpinner = new javax.swing.JSpinner();
        task2JButton = new javax.swing.JButton();
        task3HJLabel = new javax.swing.JLabel();
        task3HJSpinner = new javax.swing.JSpinner();
        task3JButton = new javax.swing.JButton();
        task3HJLabel1 = new javax.swing.JLabel();
        task4HJSpinner = new javax.swing.JSpinner();
        task4JButton = new javax.swing.JButton();
        task4HJLabel = new javax.swing.JLabel();
        task4WJSpinner = new javax.swing.JSpinner();
        task5JButton = new javax.swing.JButton();
        task6JButton = new javax.swing.JButton();
        task7JButton = new javax.swing.JButton();
        task8JButton = new javax.swing.JButton();
        task9JButton = new javax.swing.JButton();
        inputOutputJSplitPane = new javax.swing.JSplitPane();
        inputJPanel = new javax.swing.JPanel();
        loadInputFromFileJButton = new javax.swing.JButton();
        saveInputIntoFileJButton = new javax.swing.JButton();
        randomInputJButton = new javax.swing.JButton();
        inputJTableJScrollPane = new javax.swing.JScrollPane();
        inputJTable = new javax.swing.JTable();
        outputJPanel = new javax.swing.JPanel();
        outputJTabbedPane = new javax.swing.JTabbedPane();
        outputConsoleJPanel = new javax.swing.JPanel();
        systemOutJTextAreaJScrollPane = new javax.swing.JScrollPane();
        systemOutJTextArea = new javax.swing.JTextArea();
        outputScalarJPanel = new javax.swing.JPanel();
        outputJLabel = new javax.swing.JLabel();
        outputJTextField = new javax.swing.JTextField();
        outputJTableJPanel = new javax.swing.JPanel();
        outputJTableJScrollPane = new javax.swing.JScrollPane();
        outputJTable = new javax.swing.JTable();
        mainJMenuBar = new javax.swing.JMenuBar();
        lookAndFeelJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Экзамен 2018-19 (Введение в программирование)");

        task1JButton.setText("Задача 1");
        task1JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1JButtonActionPerformed(evt);
            }
        });

        task1NJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        task1NJLabel.setText("n:");

        task2NJLabel.setText("n:");

        task2NJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        task2JButton.setText("Задача 2");
        task2JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2JButtonActionPerformed(evt);
            }
        });

        task3HJLabel.setText("h:");

        task3HJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        task3JButton.setText("Задача 3");
        task3JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task3JButtonActionPerformed(evt);
            }
        });

        task3HJLabel1.setText("h:");

        task4HJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        task4JButton.setText("Задача 4");
        task4JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task4JButtonActionPerformed(evt);
            }
        });

        task4HJLabel.setText("w:");

        task4WJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        task5JButton.setText("Задача 5");
        task5JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task5JButtonActionPerformed(evt);
            }
        });

        task6JButton.setText("Задача 6");
        task6JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task6JButtonActionPerformed(evt);
            }
        });

        task7JButton.setText("Задача 7");
        task7JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task7JButtonActionPerformed(evt);
            }
        });

        task8JButton.setText("Задача 8");
        task8JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task8JButtonActionPerformed(evt);
            }
        });

        task9JButton.setText("Задача 9");
        task9JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task9JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addComponent(task1NJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task1NJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task1JButton))
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addComponent(task2NJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task2NJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task2JButton))
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addComponent(task3HJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task3HJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task3JButton))
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addComponent(task3HJLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task4HJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task4HJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task4WJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task4JButton))
                    .addComponent(task5JButton)
                    .addComponent(task6JButton)
                    .addComponent(task7JButton)
                    .addComponent(task8JButton)
                    .addComponent(task9JButton)))
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task1NJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task1NJLabel)
                    .addComponent(task1JButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task2NJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task2NJLabel)
                    .addComponent(task2JButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task3HJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task3HJLabel)
                    .addComponent(task3JButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task4HJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task3HJLabel1)
                    .addComponent(task4WJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task4HJLabel)
                    .addComponent(task4JButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task5JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task6JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task7JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task8JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task9JButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputOutputJSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        inputOutputJSplitPane.setResizeWeight(0.5);
        inputOutputJSplitPane.setToolTipText("");
        inputOutputJSplitPane.setPreferredSize(new java.awt.Dimension(542, 679));

        loadInputFromFileJButton.setText("Загрузить из файла");
        loadInputFromFileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInputFromFileJButtonActionPerformed(evt);
            }
        });

        saveInputIntoFileJButton.setText("Сохранить в файл");
        saveInputIntoFileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInputIntoFileJButtonActionPerformed(evt);
            }
        });

        randomInputJButton.setText("Заполнить случайными числами");
        randomInputJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomInputJButtonActionPerformed(evt);
            }
        });

        inputJTableJScrollPane.setViewportView(inputJTable);

        javax.swing.GroupLayout inputJPanelLayout = new javax.swing.GroupLayout(inputJPanel);
        inputJPanel.setLayout(inputJPanelLayout);
        inputJPanelLayout.setHorizontalGroup(
            inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputJTableJScrollPane)
                    .addGroup(inputJPanelLayout.createSequentialGroup()
                        .addComponent(loadInputFromFileJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveInputIntoFileJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomInputJButton)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputJPanelLayout.setVerticalGroup(
            inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJTableJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadInputFromFileJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(randomInputJButton)
                        .addComponent(saveInputIntoFileJButton)))
                .addContainerGap())
        );

        inputOutputJSplitPane.setTopComponent(inputJPanel);

        systemOutJTextArea.setColumns(20);
        systemOutJTextArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        systemOutJTextArea.setRows(5);
        systemOutJTextAreaJScrollPane.setViewportView(systemOutJTextArea);

        javax.swing.GroupLayout outputConsoleJPanelLayout = new javax.swing.GroupLayout(outputConsoleJPanel);
        outputConsoleJPanel.setLayout(outputConsoleJPanelLayout);
        outputConsoleJPanelLayout.setHorizontalGroup(
            outputConsoleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputConsoleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemOutJTextAreaJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        outputConsoleJPanelLayout.setVerticalGroup(
            outputConsoleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputConsoleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemOutJTextAreaJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        outputJTabbedPane.addTab("Результат - консоль (System.out)", outputConsoleJPanel);

        outputJLabel.setText("Результат:");

        outputJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout outputScalarJPanelLayout = new javax.swing.GroupLayout(outputScalarJPanel);
        outputScalarJPanel.setLayout(outputScalarJPanelLayout);
        outputScalarJPanelLayout.setHorizontalGroup(
            outputScalarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputScalarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        outputScalarJPanelLayout.setVerticalGroup(
            outputScalarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputScalarJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputScalarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputJLabel)
                    .addComponent(outputJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        outputJTabbedPane.addTab("Результат - скаляр", outputScalarJPanel);

        outputJTable.setEnabled(false);
        outputJTableJScrollPane.setViewportView(outputJTable);

        javax.swing.GroupLayout outputJTableJPanelLayout = new javax.swing.GroupLayout(outputJTableJPanel);
        outputJTableJPanel.setLayout(outputJTableJPanelLayout);
        outputJTableJPanelLayout.setHorizontalGroup(
            outputJTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputJTableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputJTableJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        outputJTableJPanelLayout.setVerticalGroup(
            outputJTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputJTableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputJTableJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        outputJTabbedPane.addTab("Результат - массив", outputJTableJPanel);

        javax.swing.GroupLayout outputJPanelLayout = new javax.swing.GroupLayout(outputJPanel);
        outputJPanel.setLayout(outputJPanelLayout);
        outputJPanelLayout.setHorizontalGroup(
            outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputJTabbedPane)
        );
        outputJPanelLayout.setVerticalGroup(
            outputJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputJTabbedPane)
        );

        inputOutputJSplitPane.setRightComponent(outputJPanel);

        lookAndFeelJMenu.setText("Вид");
        mainJMenuBar.add(lookAndFeelJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputOutputJSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputOutputJSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomInputJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomInputJButtonActionPerformed
        try {
            int[][] arr = ArrayUtils.createRandomIntMatrix(inputJTable.getRowCount(), inputJTable.getColumnCount(), 100);
            JTableUtils.writeArrayToJTable(inputJTable, arr);
        } catch (Exception e) {
            SwingUtils.showErrorMessageBox(e);
        }
    }//GEN-LAST:event_randomInputJButtonActionPerformed

    private void loadInputFromFileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInputFromFileJButtonActionPerformed
        try {
            if (openJFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                int[][] arr = ArrayUtils.readIntArray2FromFile(openJFileChooser.getSelectedFile().getPath());
                JTableUtils.writeArrayToJTable(inputJTable, arr);
            }
        } catch (Exception e) {
            SwingUtils.showErrorMessageBox(e);
        }
    }//GEN-LAST:event_loadInputFromFileJButtonActionPerformed

    private void saveInputIntoFileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInputIntoFileJButtonActionPerformed
        try {
            if (saveJFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                int[][] arr = JTableUtils.readIntMatrixFromJTable(inputJTable);
                String file = saveJFileChooser.getSelectedFile().getPath();
                if (!file.toLowerCase().endsWith(".txt")) {
                    file += ".txt";
                }
                ArrayUtils.writeArrayToFile(file, arr);
            }
        } catch (Exception e) {
            SwingUtils.showErrorMessageBox(e);
        }
    }//GEN-LAST:event_saveInputIntoFileJButtonActionPerformed

    private void task1JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1JButtonActionPerformed
        int n = ((Integer) task1NJSpinner.getValue()).intValue();
        showSystemOut(() -> Exam.task1(n));
    }//GEN-LAST:event_task1JButtonActionPerformed

    private void task2JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2JButtonActionPerformed
        int n = ((Integer) task2NJSpinner.getValue()).intValue();
        showSystemOut(() -> Exam.task2(n));
    }//GEN-LAST:event_task2JButtonActionPerformed

    private void task3JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task3JButtonActionPerformed
        int h = ((Integer) task3HJSpinner.getValue()).intValue();
        showSystemOut(() -> Exam.task3(h));
    }//GEN-LAST:event_task3JButtonActionPerformed

    private void task4JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task4JButtonActionPerformed
        int h = ((Integer) task4HJSpinner.getValue()).intValue();
        int w = ((Integer) task4WJSpinner.getValue()).intValue();
        showSystemOut(() -> Exam.task4(h, w));
    }//GEN-LAST:event_task4JButtonActionPerformed

    private void task5JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task5JButtonActionPerformed
        try {
            int[] array = JTableUtils.readIntArrayFromJTable(inputJTable);
            showScalar(Exam.task5(array));
        } catch(Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_task5JButtonActionPerformed

    private void task6JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task6JButtonActionPerformed
        try {
            int[][] array = JTableUtils.readIntMatrixFromJTable(inputJTable);
            showScalar(Exam.task6(array));
        } catch(Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_task6JButtonActionPerformed

    private void task7JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task7JButtonActionPerformed
        try {
            int[][] array = JTableUtils.readIntMatrixFromJTable(inputJTable);
            Exam.task7(array);
            showArray(array);
        } catch(Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_task7JButtonActionPerformed

    private void task8JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task8JButtonActionPerformed
        try {
            int[][] array = JTableUtils.readIntMatrixFromJTable(inputJTable);
            Exam.task8(array);
            showArray(array);
        } catch(Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_task8JButtonActionPerformed

    private void task9JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task9JButtonActionPerformed
        try {
            List<Integer> list = Arrays.asList(ArrayUtils.toObject(JTableUtils.readIntArrayFromJTable(inputJTable)));
            List<Integer> newList = Exam.task9(list);
            if (newList == null) {
                newList = Arrays.asList(new Integer[0]);
            }
            showArray(newList);
        } catch(Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_task9JButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JTable inputJTable;
    private javax.swing.JScrollPane inputJTableJScrollPane;
    private javax.swing.JSplitPane inputOutputJSplitPane;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton loadInputFromFileJButton;
    private javax.swing.JMenu lookAndFeelJMenu;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JPanel outputConsoleJPanel;
    private javax.swing.JLabel outputJLabel;
    private javax.swing.JPanel outputJPanel;
    private javax.swing.JTabbedPane outputJTabbedPane;
    private javax.swing.JTable outputJTable;
    private javax.swing.JPanel outputJTableJPanel;
    private javax.swing.JScrollPane outputJTableJScrollPane;
    private javax.swing.JTextField outputJTextField;
    private javax.swing.JPanel outputScalarJPanel;
    private javax.swing.JButton randomInputJButton;
    private javax.swing.JButton saveInputIntoFileJButton;
    private javax.swing.JTextArea systemOutJTextArea;
    private javax.swing.JScrollPane systemOutJTextAreaJScrollPane;
    private javax.swing.JButton task1JButton;
    private javax.swing.JLabel task1NJLabel;
    private javax.swing.JSpinner task1NJSpinner;
    private javax.swing.JButton task2JButton;
    private javax.swing.JLabel task2NJLabel;
    private javax.swing.JSpinner task2NJSpinner;
    private javax.swing.JLabel task3HJLabel;
    private javax.swing.JLabel task3HJLabel1;
    private javax.swing.JSpinner task3HJSpinner;
    private javax.swing.JButton task3JButton;
    private javax.swing.JLabel task4HJLabel;
    private javax.swing.JSpinner task4HJSpinner;
    private javax.swing.JButton task4JButton;
    private javax.swing.JSpinner task4WJSpinner;
    private javax.swing.JButton task5JButton;
    private javax.swing.JButton task6JButton;
    private javax.swing.JButton task7JButton;
    private javax.swing.JButton task8JButton;
    private javax.swing.JButton task9JButton;
    // End of variables declaration//GEN-END:variables
}
